### ISSUE TITLE
I don't get to use it, blender 3.3.0

### ISSUE THREAD

**Issue by DESAIN23** [ChemiKhazi/Sprytile#144]
Python: Traceback (most recent call last):
  File "C:\Users\T-Gamer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SpryTile\sprytile_modal.py", line 608, in modal
    self.exit_modal(event, context)
  File "C:\Users\T-Gamer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SpryTile\sprytile_modal.py", line 924, in exit_modal
    self.call_tool(event, False, context)
  File "C:\Users\T-Gamer\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\SpryTile\sprytile_modal.py", line 712, in call_tool
    build_preview=self.draw_preview,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy_types.py", line 817, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OP_SprytileModalTool' object has no attribute 'draw_preview'

**Comment by KieranCarden** [comment]
I'm getting the same error with Blender 3.1

**Comment by shinmai** [comment]
This repository hasn't been updated in 2 years, but there are forks that fix issues w.r.t. more recent Blender versions.
Just tested [this one](https://github.com/TheBricktop/Sprytile-5.25-3.2-fix) and it seems to work well, based on a quick test on 3.2.2.

YMMV with 3.3, obviously, but that should get you to 3.x at the very least.

**Comment by matotim35** [comment]
Hey, what is YMMV? Im having this same issue

**Comment by MacMiggity** [comment]
> Hey, what is YMMV? Im having this same issue

Your Mileage May Vary = you might have a different experience based on your current versions.
