### ISSUE TITLE
Error when clicking in viewport

### ISSUE THREAD

**Issue by Andyw3d** [ChemiKhazi/Sprytile#145]
When I click in the viewport I get this error.
Python: Traceback (most recent call last):
  File "C:\Users\********\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sprytile-master\sprytile_modal.py", line 608, in modal
    self.exit_modal(event, context)
  File "C:\Users\andyw\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sprytile-master\sprytile_modal.py", line 924, in exit_modal
    self.call_tool(event, False, context)
  File "C:\Users\andyw\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\Sprytile-master\sprytile_modal.py", line 712, in call_tool
    build_preview=self.draw_preview,
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\bpy_types.py", line 817, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OP_SprytileModalTool' object has no attribute 'draw_preview'

**Comment by ionthedev** [comment]
I just released an updated fork of Sprytile that fixes this issue. https://github.com/ionthedev/ReSprytile

This error only comes up when the tilemap preview window freaks out because apparently, new versions of Blender need the preview windows positional data to be converted to an integer.

Working for 3.4.0
