### ISSUE TITLE
AttributeError: 'VIEW3D_OP_SprytileModalTool' object has no attribute 'draw_preview'

### ISSUE THREAD

**Issue by denisxab** [ChemiKhazi/Sprytile#146]
Python: Traceback (most recent call last):
  File "/home/denis/.config/blender/3.0/scripts/addons/SpryTile/sprytile_modal.py", line 608, in modal
    self.exit_modal(event, context)
  File "/home/denis/.config/blender/3.0/scripts/addons/SpryTile/sprytile_modal.py", line 924, in exit_modal
    self.call_tool(event, False, context)
  File "/home/denis/.config/blender/3.0/scripts/addons/SpryTile/sprytile_modal.py", line 712, in call_tool
    build_preview=self.draw_preview,
  File "/usr/share/blender/scripts/modules/bpy_types.py", line 738, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OP_SprytileModalTool' object has no attribute 'draw_preview'

location: <unknown location>:-1

**Comment by krorzn** [comment]
**same exact error**
running blender `3.4.0`
It happens right after I click on `Sprytile Build` tool
also the tile selector at the bottom left never appears.

**Comment by briakitten** [comment]
Same here on this issue, before this point I wasn't able to load the texture image into the sidebar, before eventually getting it through "add tile." I don't know if this is related.

**Comment by Nemasys** [comment]
I get this same error as soon as I click on the tile palette, and then the tile palette disappears and I am no longer able to build or paint.  Once the error occurs, it pops up every time I click in the viewport with any of the Sprytile tools selected.

Blender 3.4.1 (fresh install)

**Comment by TyPhyter** [comment]
adding to what @Nemasys pointed out, I get the error any time I try to interact with the tile palette in any way, either clicking, scrolling to zoom, or shift+middle mouse to move it. 

Blender 3.4.1 as well

**Comment by tamarasahara** [comment]
i also have this error, has anyone tried if it works with older blender versions yet?

**Comment by briakitten** [comment]
I had it solved by moving to Blender 2.9. It's not supported for newer versions of blender like 3.0+, so for anyone having this issue too it's likely due to version incompatibility.

**Comment by ionthedev** [comment]
I just released an updated fork of Sprytile that fixes this issue. https://github.com/ionthedev/ReSprytile

This error only comes up when the tilemap preview window freaks out because apparently, new versions of Blender need the preview windows positional data to be converted to an integer.

Working for 3.4.0
