### ISSUE TITLE
Palette doesn't move then disappears

### ISSUE THREAD

**Issue by A1998ToyotaCorolla** [ChemiKhazi/Sprytile#147]
When I try to move the palette, I get a python error then the palette completely disappears. Here is the error I got:

Python: Traceback (most recent call last):
  File "C:\Users\-------\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SpryTile\sprytile_gui.py", line 205, in modal
    ret_val = self.handle_ui(context, event)
  File "C:\Users\-------\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\SpryTile\sprytile_gui.py", line 475, in handle_ui
    context.scene.sprytile_ui.palette_pos[0] = display_offset.x
TypeError: expected an int type

**Comment by andresTapari** [comment]
it happened to me, i had moved the image from the original folder, i also had to restart blender.

**Comment by MortMort89** [comment]
Hey, it's hard to tell without having full context, I would suggest asking
on the official Discord: https://discord.com/invite/Uu7ZKv2x
