### ISSUE TITLE
v0.2.6: Workflow panel empty

### ISSUE THREAD

**Issue by not-surt** [ChemiKhazi/Sprytile#30]
The workflow panel is now empty for me in v0.2.6.

**Comment by ChemiKhazi** [comment]
If you're on Windows, can you please try launching blender from the command line and reporting any error?

**Comment by not-surt** [comment]
Sorry, was using with development version of blender, tried with official release and is showing up fine now.

Not using windows, but the is the console output:
```
Read prefs: /home/surt/.config/blender/2.78/config/userpref.blend
sprytile updater verbose is enabled
Read in json settings from file
Running background check for update
Traceback (most recent call last):
  File "/home/surt/.config/blender/2.78/scripts/addons/SpryTile/sprytile_utils.py", line 843, in draw
    row.label("", icon="VIEW3D_VEC")
TypeError: UILayout.label(): error with keyword argument "icon" -  enum "VIEW3D_VEC" not found in ('NONE', 'QUESTION', 'ERROR', 'CANCEL', 'TRIA_RIGHT', 'TRIA_DOWN', 'TRIA_LEFT', 'TRIA_UP', 'ARROW_LEFTRIGHT', 'PLUS', 'DISCLOSURE_TRI_DOWN', 'DISCLOSURE_TRI_RIGHT', 'RADIOBUT_OFF', 'RADIOBUT_ON', 'MENU)

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/surt/.config/blender/2.78/scripts/addons/SpryTile/sprytile_utils.py", line 843, in draw
    row.label("", icon="VIEW3D_VEC")
TypeError: UILayout.label(): error with keyword argument "icon" -  enum "VIEW3D_VEC" not found in ('NONE', 'QUESTION', 'ERROR', 'CANCEL', 'TRIA_RIGHT', 'TRIA_DOWN', 'TRIA_LEFT', 'TRIA_UP', 'ARROW_LEFTRIGHT', 'PLUS', 'DISCLOSURE_TRI_DOWN', 'DISCLOSURE_TRI_RIGHT', 'RADIOBUT_OFF', 'RADIOBUT_ON', 'MENU)

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/surt/.config/blender/2.78/scripts/addons/SpryTile/sprytile_utils.py", line 843, in draw
    row.label("", icon="VIEW3D_VEC")
TypeError: UILayout.label(): error with keyword argument "icon" -  enum "VIEW3D_VEC" not found in ('NONE', 'QUESTION', 'ERROR', 'CANCEL', 'TRIA_RIGHT', 'TRIA_DOWN', 'TRIA_LEFT', 'TRIA_UP', 'ARROW_LEFTRIGHT', 'PLUS', 'DISCLOSURE_TRI_DOWN', 'DISCLOSURE_TRI_RIGHT', 'RADIOBUT_OFF', 'RADIOBUT_ON', 'MENU)

location: <unknown location>:-1

location: <unknown location>:-1
```

**Comment by ChemiKhazi** [comment]
Thanks for taking the time to get the console output. I wonder if it's a symptom of upgrading the addon without disabling it first. I upgraded my copy on the 2.78 install I have for testing and the same thing seemed to happen to me. Hopefully with the addon updater this wouldn't happen again. Closing this issue for now.
