### ISSUE TITLE
Error when trying to save while tile paint mode is open.

### ISSUE THREAD

**Issue by ChemiKhazi** [ChemiKhazi/Sprytile#39]
Traceback (most recent call last):
  File "C:\Users\Jeiel\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons_contrib\sprytile\sprytile_modal.py", line 926, in modal
    view_axis = self.find_view_axis(context)
  File "C:\Users\Jeiel\AppData\Roaming\Blender Foundation\Blender\2.77\scripts\addons_contrib\sprytile\sprytile_modal.py", line 417, in find_view_axis
    view_vector = view3d_utils.region_2d_to_vector_3d(region, rv3d, coord)
  File "C:\Installers\Blender277\2.77\scripts\modules\bpy_extras\view3d_utils.py", line 46, in region_2d_to_vector_3d
    viewinv = rv3d.view_matrix.inverted()
AttributeError: 'NoneType' object has no attribute 'view_matrix'

**Comment by ChemiKhazi** [comment]
Fixed in dev branch.
